### ISSUE TITLE
fix scroll bar on a-frame code example

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/vr-mozilla-org#12]
![image](https://user-images.githubusercontent.com/1560884/28944044-e511d324-7855-11e7-81fb-9835684badc0.png)

**Comment by slightlyoffbeat** [comment]
Right now this is as intended. The goal is for the code to seem simple and inviting. Having it wrap made it harder to scan, so opted to allow scroll on overflow. I struggled with this, so open to ideas.

**Comment by caseyyee** [comment]
Keeping the scroll bar makes sense 👍 

It was really just a comment on the scroll bar styling.  Even having it aligned to the bottom of the element would make it look better?

**Comment by slightlyoffbeat** [comment]
Agree. Scrollbars are tricky. Browsers show them differently depending on system resources. For me it looks like this in FF/Chrome:
<img width="684" alt="screenshot 2017-08-03 14 57 12" src="https://user-images.githubusercontent.com/2030656/28945633-22523d40-785c-11e7-9b8b-938baf33abe8.png">

I've found that forcing a style has a lot of unwanted side effects, but I also haven't tried to do that for several years. I'll investigate.
