### ISSUE TITLE
`<script async>` leading to unpredictable order of execution of scripts

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#17]
notice in the `<head>` the `<script>`s defined and their dependencies: https://github.com/MozVR/vr-mozilla-org/blob/33a8387/components/layout/Meta.js#L30-L35

should use `defer` or move them all to above `</body>`

**Comment by slightlyoffbeat** [comment]
using gatsby's plugin for GA now. Closing.
