### ISSUE TITLE
reduce height and text line-height of "Mixed Reality for the Open Web" header

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#29]
![screen shot 2018-09-12 at 15 18 37](https://user-images.githubusercontent.com/203725/45456325-316bbe00-b69f-11e8-875b-c18c6e50b639.png)
![screen shot 2018-09-12 at 15 17 29](https://user-images.githubusercontent.com/203725/45456335-392b6280-b69f-11e8-8330-a36dcbc6e2d6.png)
![screen shot 2018-09-12 at 15 17 22](https://user-images.githubusercontent.com/203725/45456336-392b6280-b69f-11e8-9356-7611a30d9dfc.png)
![screen shot 2018-09-12 at 15 17 12](https://user-images.githubusercontent.com/203725/45456337-392b6280-b69f-11e8-9152-0d15181c9076.png)

**Comment by cvan** [comment]
![image](https://user-images.githubusercontent.com/203725/45457498-06379d80-b6a4-11e8-89a0-cd745c0f8a68.png)
![image](https://user-images.githubusercontent.com/203725/45457501-08016100-b6a4-11e8-9851-ca4c340fdf78.png)

**Comment by slightlyoffbeat** [comment]
done.
