### ISSUE TITLE
add a bottom margin to the footer

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#30]
the left and right sides have a margin, but the footer is flushed to the bottom. could probably use the same margin as on the left and right sides, or make the footer bleed out to the left and right edges (no margin).

![img_3789](https://user-images.githubusercontent.com/203725/45456420-890a2980-b69f-11e8-9fda-75d2fea30912.jpeg)

**Comment by slightlyoffbeat** [comment]
I added a margin on mobile which is where this is most noticeable. I'll run this by the designers for suggestions on desktop, or future improvements. Closing for now.
