### ISSUE TITLE
replace the "WebVR Showcase" card with "Submit your WebVR creations"

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#31]
![image](https://user-images.githubusercontent.com/203725/45456561-236a6d00-b6a0-11e8-9f6b-e5005c4a5536.png)

currently this card links to an [out-of-date Airtable](https://airtable.com/embed/shr2Lc7pmlJis02R4/tblZbV2S0W0T5DDth?viewControls=on).

currently, we're not sure if we want the FxR Content Feed to be intended for public consumption outside of Firefox Reality just  yet.

I'm working with @joshmarinacci to create a user/developer-facing form (à la Google Forms) using Airtable to accept submissions for possible inclusion in the curated FxR Content Feed.

(you can use [this link](https://airtable.com/invite/l?inviteId=invwDplI1O661a6OY&inviteToken=ede68c8cf8ef37cd51c32e86bd8fb6a733a09b45f1afba479aaa6b3f1f025e08) to join our FxR Content Feed Airtable.)

**Comment by cvan** [comment]
here's a public link to Airtable submission form: https://airtable.com/shrHKZrLcGJhXNVuH

**Comment by slightlyoffbeat** [comment]
Done. Had to change copy because of character limits.
