### ISSUE TITLE
should the background color of the cards section be white instead of gray?

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#32]
just a nit. wasn't sure if this was an intentional design decision. let me know.

![screen shot 2018-09-12 at 15 26 02](https://user-images.githubusercontent.com/203725/45456603-472db300-b6a0-11e8-9c6b-1058c67dcbe9.png)
![screen shot 2018-09-12 at 15 26 07](https://user-images.githubusercontent.com/203725/45456602-472db300-b6a0-11e8-825b-ba557a74a3fe.png)
![screen shot 2018-09-12 at 15 26 11](https://user-images.githubusercontent.com/203725/45456601-472db300-b6a0-11e8-8459-5dc4f6294e11.png)

**Comment by slightlyoffbeat** [comment]
intentional from designers. Closing for now, but this will be revisited when we do a larger redesign a few months from now.
