### ISSUE TITLE
increase click targets for Firefox Reality masthead (and cards)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#33]
especially with the link appearing below the fold at mobile and desktop widths, the "Learn More" link could be easily missed. if we created a clickable target around the entire masthead (and the other cards if you're game), it would help a lot with click-through rates.

![image](https://user-images.githubusercontent.com/203725/45456633-6a586280-b6a0-11e8-8699-7aa9ab53bcc2.png)

![image](https://user-images.githubusercontent.com/203725/45456628-662c4500-b6a0-11e8-8139-14b8cff1e1da.png)

**Comment by slightlyoffbeat** [comment]
done. Added a little hover effect as well.

**Comment by cvan** [comment]
I noticed the effect on the Hubs and A-Painter cards: looks awesome!

could we add a similar effect for Firefox Reality's card? I see the "Learn More" link is bigger, but it feels like we should really make the whole masthead clickable. wasn't sure if this was intentional or not.

**Comment by cvan** [comment]
reopening this per my comment above. apologies if this is already on your radar or was an intentional design decision. thanks!

**Comment by cvan** [comment]
I see this now. perfect, and nice effect :+1: thank you!
