### ISSUE TITLE
Obscured text in Hubs and A-Frame cards at widths <= 450px, <= 315px

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#35]
Hubs card at width <= 450px:

![screen shot 2018-09-12 at 15 34 28](https://user-images.githubusercontent.com/203725/45456892-582af400-b6a1-11e8-980d-9fe5a980f0aa.png)
![screen shot 2018-09-12 at 15 34 22](https://user-images.githubusercontent.com/203725/45456893-582af400-b6a1-11e8-9631-dfa50250e287.png)
![screen shot 2018-09-12 at 15 34 13](https://user-images.githubusercontent.com/203725/45456894-582af400-b6a1-11e8-8736-6eca0a088671.png)

also see the overlap in the A-Painter card at around width <= 315px:

![screen shot 2018-09-12 at 15 34 50](https://user-images.githubusercontent.com/203725/45456901-6711a680-b6a1-11e8-9c3a-83f7594f5414.png)

possible solution: remove tags at mobile widths? or make them smaller, `display: block` the parent, and position the tags as `inline-lock` below the CTA links?

**Comment by slightlyoffbeat** [comment]
removing at mobile is the best solution for now. done.
