### ISSUE TITLE
Use Glitch link for A-Frame example (instead of old CodePen)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#37]
![screen shot 2018-09-12 at 15 39 27](https://user-images.githubusercontent.com/203725/45457046-0afb5200-b6a2-11e8-92c9-1394ac982577.png)

- "View and edit an example on Codepen" -> "View and edit an example on Glitch"
- https://codepen.io/mozvr/pen/BjygdO -> https://glitch.com/~aframe

if you want to get fancy, you could even use this "Remix on Glitch" image:

[![Remix on Glitch](https://cdn.glitch.com/2703baf2-b643-4da7-ab91-7ee2a2d00b5b%2Fremix-button.svg)](https://glitch.com/edit/#!/remix/aframe)

**Comment by slightlyoffbeat** [comment]
great call. Added.
