### ISSUE TITLE
update content tiles so that they are mozvr projects

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/vr-mozilla-org#4]
some options.

puzzle rain:
https://mozvr.com/puzzle-rain/

a-saturday-night:
https://aframe.io/a-saturday-night

a-shooter:
https://aframe.io/a-blast/

or a blog post:
https://blog.mozvr.com/webvr-india-community-conducts-webvr-hack-night/

cc @cvan for some options as well.

**Comment by cvan** [comment]
I was thinking it'd be nice to show a bunch of cool photos of community members and events of people using A-Frame.

I like the grid of photos used on this site:
https://bakkenbaeck.com/jobs

I can collect a bunch of Community photos from the [A-Frame Blog](https://aframe.io/blog/).

There's an Events section in the A Week of A-Frame posts, many of which contain good photos of community members in action.

<hr>

A good A-Frame-powered community project to feature that's responsive on mobile and desktop (with some nitpick enhancements IMO to address):

**BeBlock** by Fasility
- https://twitter.com/aframevr/status/892362454323281920
- https://twitter.com/ktrogolo/status/892441210262102016
- https://twitter.com/Fasility_VR/status/892173982392348672
- https://twitter.com/meganhaddadi/status/888498611885137920

<hr>

http://whereishere.xyz/ is a good project.

I have a whole list, with compatibility reports I've recorded for each, from various headset/platform setups. I'll circulate it when it's ready. (I have some basic JavaScript feature-detection code that auto-filters compatible projects for the user's device, and I also show archived/old projects [with videos] that are for devices/headsets that the user is not currently on/have.)

**Comment by slightlyoffbeat** [comment]
Updated to show off projects such as hubs, Unity tool, and more. Also FFR. Can open a new issue if there are new things add.
