### ISSUE TITLE
update "Designed from the Virtual Ground Up" headset screenshot of Content Feed with latest version

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#41]
![screen shot 2018-09-12 at 15 44 00](https://user-images.githubusercontent.com/203725/45457219-ccb26280-b6a2-11e8-902a-bb969ce9eef4.png)

first off, amazing screenshot! I love it 👍

there were a couple minor changes (the WITHIN background-color, the `max-width` of the card titles, and a few other items) since that screenshot was taken.

**Comment by slightlyoffbeat** [comment]
updated.
