### ISSUE TITLE
fix overlapped text and center background-images in "Built by Mozilla" section at mobile widths

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#42]
![image](https://user-images.githubusercontent.com/203725/45457520-25cec600-b6a4-11e8-89e9-062b1211dfef.png)
![screen shot 2018-09-12 at 15 45 24](https://user-images.githubusercontent.com/203725/45457510-1c455e00-b6a4-11e8-9d1a-21ae7ba8cc35.png)

**Comment by slightlyoffbeat** [comment]
fixed!

**Comment by cvan** [comment]
nice fix here! :+1:
