### ISSUE TITLE
add platform/OS icons in desktop "Firefox" card (below "Firefox Reality" masthead)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#44]
![screen shot 2018-09-12 at 15 50 15](https://user-images.githubusercontent.com/203725/45457402-9e815280-b6a3-11e8-8eab-331fe5b8a5d7.png)

it could get confusing seeing Firefox below Firefox Reality, without an image or text that we're referring to Firefox desktop. I had to click the [**Get it Now**](https://www.mozilla.org/firefox/new/) link to get it.

perhaps we could add a Windows icon (and soon macOS and Linux) for now next to the link?

**Comment by slightlyoffbeat** [comment]
Added "Desktop" and moved it down, but leaving this open to explore icon options.
