### ISSUE TITLE
reduce letter-spacing of "New!" ribbon on "Firefox Reality" masthead

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#45]
![img_3778](https://user-images.githubusercontent.com/203725/45457463-e99b6580-b6a3-11e8-95c6-c03fdc438bd2.jpeg)

I'd change `N e w !` to `NEW` and reduce the letter-spacing

**Comment by slightlyoffbeat** [comment]
Done and Done
