### ISSUE TITLE
fix improperly wrapped nav links (and line-height) in header at mobile-ish widths

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#46]
![image](https://user-images.githubusercontent.com/203725/45457539-3e3ee080-b6a4-11e8-866c-feddd98869fb.png)
![screen shot 2018-09-12 at 15 17 12](https://user-images.githubusercontent.com/203725/45457546-4bf46600-b6a4-11e8-8756-5c9871cbaede.png)
![screen shot 2018-09-12 at 15 17 05](https://user-images.githubusercontent.com/203725/45457547-4bf46600-b6a4-11e8-9391-e060eb2f815c.png)
![screen shot 2018-09-12 at 15 17 03](https://user-images.githubusercontent.com/203725/45457548-4bf46600-b6a4-11e8-9c9a-41be15c9c19c.png)

**Comment by slightlyoffbeat** [comment]
Line height has been fixed. I actually meant to remove a-frame from header, which solves the other problem for now. I'll open a new issue to have a better mobile nav that can be scaled.
