### ISSUE TITLE
add "Blog" link to footer as well

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#47]
the "Blog" link appears in the header, but with all the scrolling, users may forget about it. might be nice to add "Mixed Reality Blog" to the the "Additional Links" section.

![screen shot 2018-09-12 at 15 57 17](https://user-images.githubusercontent.com/203725/45457603-a42b6800-b6a4-11e8-9862-2fdb40d18371.png)
![screen shot 2018-09-12 at 15 57 23](https://user-images.githubusercontent.com/203725/45457606-a5f52b80-b6a4-11e8-9225-db6d84c65f21.png)

and perhaps also "Firefox Reality" while we're at it?

**Comment by slightlyoffbeat** [comment]
added both. Also removed a-frame blog and WebVR spec for now, in an effort to continue to make this more consumer-facing.
