### ISSUE TITLE
use VIVEPORT logo for "HTC VIVEPORT" on Firefox Reality page

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#48]
https://fxr-staging.now.sh/firefox-reality

![image](https://user-images.githubusercontent.com/203725/45576230-352c4b80-b82b-11e8-8f1b-4e9112c461c6.png)

**Comment by cvan** [comment]
https://www.viveport.com/vr-store-assets/viveport-blue-white.svg

**Comment by slightlyoffbeat** [comment]
fixed.

**Comment by cvan** [comment]
![76d66f92-d10e-4e35-880e-cd309090a08c](https://user-images.githubusercontent.com/203725/45646864-5bdfc180-ba79-11e8-92f0-b9ed81dd6b4f.png)

could you fix the padding/size at mobile widths?
