### ISSUE TITLE
vertically center FxR app-store icons 

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#49]
https://fxr-staging.now.sh/firefox-reality

tablet/mobile width:
![image](https://user-images.githubusercontent.com/203725/45576295-758bc980-b82b-11e8-92a6-781f7cd1a68f.png)

larger width:
![image](https://user-images.githubusercontent.com/203725/45576287-70c71580-b82b-11e8-8b81-c00ceaefa87c.png)

**Comment by slightlyoffbeat** [comment]
@cvan Because of some of the extra css/divs added to enable the hover, this is complicated a bit. Have to do so manually at the breakpoints. Mobile is a bit better now. Closing, but feel free to re -open.

**Comment by cvan** [comment]
I noticed, yeah - I think it's good. at some narrower desktop widths, the hover effect seems to make the non-centered position more obvious:

![image](https://user-images.githubusercontent.com/203725/45663257-5b1b4f80-baba-11e8-9b41-0796afc04377.png)

not a huge deal. looks good to me.
