### ISSUE TITLE
change out vrlist for list of sites curated by the team

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/vr-mozilla-org#5]
cc @cvan

VRList isn't good.  Many of the examples don't work.  We should make sure that examples we point to function with Firefox.

**Comment by slightlyoffbeat** [comment]
I'm happy to point to another list, but I'll need a link. Otherwise, this works for now. This is what is currently linked to from the header of mozvr.com.

**Comment by caseyyee** [comment]
Yup we're working on one.  keep it as is for now, just wanted to track this.

**Comment by slightlyoffbeat** [comment]
awesome. Looking forward to it :)

**Comment by cvan** [comment]
you can assign me this issue. link will be sent when ready. thanks!

**Comment by slightlyoffbeat** [comment]
showcase has been removed. There's another open issue for creating our own page. Closing.
