### ISSUE TITLE
consider adding a "Downloads" heading above the app-store icons on FxR page

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#50]
![image](https://user-images.githubusercontent.com/203725/45576333-97854c00-b82b-11e8-8ac3-5a4bffecbc83.png)

![image](https://user-images.githubusercontent.com/203725/45576354-a8ce5880-b82b-11e8-8207-bf1318ceb7db.png)

**Comment by slightlyoffbeat** [comment]
added it on mobile.

**Comment by cvan** [comment]
looks good, thanks!
