### ISSUE TITLE
bottom of Firefox Desktop clipped at widths between ~940-957px

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#52]
![image](https://user-images.githubusercontent.com/203725/45576410-e6cb7c80-b82b-11e8-9c08-c45d63571257.png)

![image](https://user-images.githubusercontent.com/203725/45576415-ecc15d80-b82b-11e8-9652-34eb87353a4a.png)

**Comment by slightlyoffbeat** [comment]
These cards should be rebuilt or redesigned to be more robust, but for now I shortened the character count a bit. We can open a new issue for solving the larger issue.
