### ISSUE TITLE
capitalise "i" in "Internet"

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#54]
![image](https://user-images.githubusercontent.com/203725/45576680-0a42f700-b82d-11e8-9e32-2a306bcf392f.png)

vs.

![image](https://user-images.githubusercontent.com/203725/45576675-0616d980-b82d-11e8-9b09-62f07d1075df.png)

**Comment by slightlyoffbeat** [comment]
👍
