### ISSUE TITLE
perhaps replace A-Blast with more family-friendly art

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#55]
heh, probably not the juxtaposition: of the A-Blast shooter game next to a kid wearing a VR headset.

![image](https://user-images.githubusercontent.com/203725/45576692-1dee5d80-b82d-11e8-8200-451e066058d6.png)

perhaps use a screen grab from [Puzzle Rain](https://mixedreality.mozilla.org/puzzle-rain/) or something?

![](https://raw.githubusercontent.com/MozillaReality/puzzle-rain/master/app/images/bg.jpg)

**Comment by slightlyoffbeat** [comment]
👍
