### ISSUE TITLE
use relative, not absolute, paths

### ISSUE THREAD

**Issue by cvan** [MozillaReality/vr-mozilla-org#9]
To be portable (if https://vr.mozilla.org/ becomes https://mozilla.org/vr/, for example), URLs should be relative (e.g., `../path/img.png`), not absolute (e.g., `/path/img.png`).

https://cvan.io/mozvr.github.io/

**Comment by slightlyoffbeat** [comment]
@caseyyee @cvan https://github.com/MozVR/vr-mozilla-org/pull/11

**Comment by slightlyoffbeat** [comment]
fixed by switching to gatsby
